# Generated by Django 4.2.14 on 2024-12-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_halltype_seatingtemplate_zone_alter_hall_options_and_more'),
        ('sessions_movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('column', models.IntegerField(verbose_name='Место в ряду')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='sessions_movie.session', verbose_name='Сеанс')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halls.zone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'unique_together': {('session', 'row', 'column')},
            },
        ),
    ]
