# Generated by Django 4.2.14 on 2024-12-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_movie', '0003_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала сеанса'),
        ),
    ]
