# Generated by Django 4.2.14 on 2024-12-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_movie', '0007_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sessions_movie.session', verbose_name='Сеанс'),
            preserve_default=False,
        ),
    ]
