# Generated by Django 4.2.14 on 2024-12-15 06:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина имени — 2 символа')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина фамилии — 2 символа')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='director',
            name='middle_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Минимальная длина отчества — 2 символа')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='annotation',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Минимальная длина аннотации — 100 символов'), django.core.validators.MaxLengthValidator(300, 'Максимальная длина аннотации — 300 символов')], verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=60), help_text='Максимальная продолжительность фильма — 360 минут', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Минимальная длина названия фильма — 3 символов'), django.core.validators.MaxLengthValidator(50, 'Максимальная длина названия фильма — 50 символов')], verbose_name='Название'),
        ),
    ]
