# Generated by Django 4.2.14 on 2024-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_director_first_name_alter_director_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Жанр'),
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('first_name', 'last_name', 'middle_name')},
        ),
    ]
