# Generated by Django 4.2.14 on 2024-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_country_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
