# Generated by Django 4.2.14 on 2024-12-15 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=1, help_text='Максимальная продолжительность фильма — 360 минут', validators=[django.core.validators.MaxValueValidator(360)], verbose_name='Длительность'),
            preserve_default=False,
        ),
    ]
