# Generated by Django 4.2.14 on 2024-12-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.RemoveField(
            model_name='director',
            name='middle_name',
        ),
    ]
