# Generated by Django 4.2.14 on 2024-12-15 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_director_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(help_text='Максимальная продолжительность фильма — 360 минут', validators=[django.core.validators.MaxValueValidator(360)], verbose_name='Длительность (минуты)'),
        ),
    ]
