# Generated by Django 4.2.14 on 2024-12-15 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='base_ticket_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(200)], verbose_name='Базовая стоимость билета'),
        ),
    ]
