# Generated by Django 4.2.14 on 2024-12-15 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_rename_name_halltype_type_remove_zone_name_zone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Номер зала'),
        ),
    ]
