# Generated by Django 4.2.14 on 2024-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0005_alter_hall_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seatingtemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='seatingtemplate',
            name='type',
            field=models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('big', 'Большой')], default=1, max_length=10, unique=True, verbose_name='Тип шаблона'),
            preserve_default=False,
        ),
    ]
