# Generated by Django 4.2.14 on 2024-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_remove_seatingtemplate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.CharField(choices=[('middle', 'Средняя зона'), ('ordinary', 'Обычная зона')], max_length=10, unique=True, verbose_name='Тип зоны'),
        ),
    ]
